# Generated by Django 2.2.6 on 2020-02-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20200201_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='menu',
            field=models.ManyToManyField(blank=True, to='crm.Menu'),
        ),
    ]
