# Generated by Django 2.2.6 on 2020-02-01 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_role_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='menu',
            new_name='menus',
        ),
    ]
