# Generated by Django 2.2.6 on 2020-02-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_userprofile_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='roles',
        ),
    ]
